// SANDBOX BUILD — runtime-AJV shim (NOT the zero-runtime-dep bundle build-validators.mjs produces).
//
// The canonical validators.mjs is an esbuild-bundled, zero-runtime-dependency file generated by
// `npm run build` (build-validators.mjs). esbuild could not be installed in the build environment
// used here (corporate CA blocks the npm registry and esbuild is not cached), so this file is the
// equivalent runtime shim instead: it loads AJV (vendored under ./node_modules), compiles the JSON
// Schemas in ../schemas at import time, and exports the SAME six validators with the SAME interface
// (each is an AJV validate function exposing `.errors`). Behaviour is identical to the bundle; the
// only difference is that AJV is required at runtime rather than inlined.
//
// To regenerate the real zero-dep bundle where the npm registry is reachable:
//   ( cd skills/audit/scripts && npm install && npm run build )
// which overwrites this file with the esbuild output.
//
// Bundles AJV (MIT License, https://github.com/ajv-validator/ajv).
import Ajv from "ajv/dist/2020.js";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "schemas");

const ajv = new Ajv({ allErrors: true, strict: false });
for (const file of readdirSync(schemasDir).filter((f) => f.endsWith(".schema.json"))) {
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  ajv.addSchema(schema, schema.$id);
}

export const finding = ajv.getSchema("finding.schema.json");
export const finalFinding = ajv.getSchema("final-finding.schema.json");
export const analyzerResponse = ajv.getSchema("analyzer-response.schema.json");
export const chain = ajv.getSchema("chain.schema.json");
export const verdict = ajv.getSchema("verdict.schema.json");
export const verifierResponse = ajv.getSchema("verifier-response.schema.json");
